# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-12-23T02:36:26+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class EvaluationResponseDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    result: Annotated[
        dict[str, Any] | None,
        Field(description='Resultado de la evaluación de la decisión.', title='Result'),
    ] = None
    performance: Annotated[
        str | None,
        Field(
            description='Métricas de ejecución si están disponibles.',
            examples=['2.5ms'],
            title='Performance',
        ),
    ] = None
    trace: Annotated[
        dict[str, Any] | None,
        Field(
            description='Información de trazabilidad para depuración.', title='Trace'
        ),
    ] = None
    source_id: Annotated[
        str | None,
        Field(
            description='ID del owner/source que proporcionó la decisión (user_id, TENANT, SYSTEM).',
            examples=['user-123', 'TENANT', 'SYSTEM'],
            title='Source Id',
        ),
    ] = None


class JDMDecisionRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    tenant_id: Annotated[str, Field(title='Tenant Id')]
    user_id: Annotated[str | None, Field(title='User Id')] = None
    decision: Annotated[str | None, Field(title='Decision')] = 'MAIN'
    content: Annotated[dict[str, Any], Field(title='Content')]


class JDMDecisionResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    decision: Annotated[str, Field(title='Decision')]
    owner: Annotated[str, Field(title='Owner')]
    content: Annotated[dict[str, Any], Field(title='Content')]


class MatchCondition(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    equals: Annotated[str | None, Field(title='Equals')] = None
    contains: Annotated[str | None, Field(title='Contains')] = None
    regex: Annotated[str | None, Field(title='Regex')] = None


class RuleOutputsPayload(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    category_l0_literal: Annotated[str | None, Field(title='Category L0 Literal')] = (
        None
    )
    category_l0_expression: Annotated[
        str | None, Field(title='Category L0 Expression')
    ] = None
    category_l1_literal: Annotated[str | None, Field(title='Category L1 Literal')] = (
        None
    )
    category_l1_expression: Annotated[
        str | None, Field(title='Category L1 Expression')
    ] = None
    category_l2_literal: Annotated[str | None, Field(title='Category L2 Literal')] = (
        None
    )
    category_l2_expression: Annotated[
        str | None, Field(title='Category L2 Expression')
    ] = None


class RulePayload(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    id: Annotated[str | None, Field(title='Id')] = None
    conditions: Annotated[dict[str, MatchCondition], Field(title='Conditions')]
    outputs: RuleOutputsPayload


class RuleType(StrEnum):
    pre_enrich = 'pre_enrich'
    post_enrich = 'post_enrich'


class RulesDecisionResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    decision: Annotated[str, Field(title='Decision')]
    rule_type: RuleType
    owner: Annotated[str, Field(title='Owner')]
    rules: Annotated[list[RulePayload], Field(title='Rules')]


class RulesUpsertRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    tenant_id: Annotated[str, Field(title='Tenant Id')]
    user_id: Annotated[str | None, Field(title='User Id')] = None
    decision: Annotated[str | None, Field(title='Decision')] = 'MAIN'
    rule_type: RuleType
    rules: Annotated[list[RulePayload], Field(title='Rules')]


class TransactionDataDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    transaction_id: Annotated[
        str,
        Field(
            description='Identificador único de la transacción.',
            examples=['tx-001', 'transaction-12345'],
            min_length=1,
            title='Transaction Id',
        ),
    ]
    amount: Annotated[
        float | None,
        Field(
            description='Monto de la transacción.',
            examples=[1500.0, 250.5],
            title='Amount',
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description='Código de moneda (ISO 4217).',
            examples=['MXN', 'USD', 'EUR'],
            title='Currency',
        ),
    ] = None
    movement_type: Annotated[
        str | None,
        Field(
            description='Tipo de movimiento.',
            examples=['income', 'outcome'],
            title='Movement Type',
        ),
    ] = None
    account_holder_type: Annotated[
        str | None,
        Field(
            description='Tipo de titular de cuenta.',
            examples=['consumer', 'business'],
            title='Account Holder Type',
        ),
    ] = None
    category: Annotated[
        str | None,
        Field(
            description='Categoría de la transacción.',
            examples=['Electronics', 'Food', 'Transport'],
            title='Category',
        ),
    ] = None
    merchant_name: Annotated[
        str | None,
        Field(
            description='Nombre del comercio.',
            examples=['Amazon', 'Starbucks', 'Walmart'],
            title='Merchant Name',
        ),
    ] = None
    merchant_id: Annotated[
        str | None, Field(description='ID del comercio.', title='Merchant Id')
    ] = None
    description: Annotated[
        str | None,
        Field(
            description='Descripción de la transacción.',
            examples=['Compra en línea', 'Pago de servicio'],
            title='Description',
        ),
    ] = None
    reference: Annotated[
        str | None,
        Field(description='Referencia de la transacción.', title='Reference'),
    ] = None
    transaction_date: Annotated[
        str | None,
        Field(
            description='Fecha de la transacción (ISO 8601).',
            examples=['2025-11-20T10:30:00Z'],
            title='Transaction Date',
        ),
    ] = None


class TransactionEvaluationResultDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    transaction_id: Annotated[
        str,
        Field(description='Identificador de la transacción.', title='Transaction Id'),
    ]
    result: Annotated[
        dict[str, Any] | None,
        Field(description='Resultado de la evaluación.', title='Result'),
    ] = None
    performance: Annotated[
        str | None,
        Field(
            description='Métricas de ejecución si están disponibles.',
            title='Performance',
        ),
    ] = None
    trace: Annotated[
        dict[str, Any] | None,
        Field(
            description='Información de trazabilidad para depuración.', title='Trace'
        ),
    ] = None
    source_id: Annotated[
        str | None,
        Field(
            description='ID del owner/source que proporcionó la decisión (user_id, TENANT, SYSTEM).',
            title='Source Id',
        ),
    ] = None
    error: Annotated[
        str | None,
        Field(description='Mensaje de error si la evaluación falló.', title='Error'),
    ] = None


class TransactionFlowContextDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    flow_type: Annotated[
        Literal['transaction'],
        Field(description='Tipo de flujo para transacciones.', title='Flow Type'),
    ] = 'transaction'
    data: Annotated[
        TransactionDataDTO | None,
        Field(description='Datos tipados del contexto de la transacción.'),
    ] = None


class ValidationError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class BodyImportRulesFromExcelDecisionsRulesImportExcelPost(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    file: Annotated[
        bytes, Field(description='Archivo Excel con las reglas', title='File')
    ]
    tenant_id: Annotated[str, Field(description='ID del tenant', title='Tenant Id')]
    rule_type: Annotated[RuleType, Field(description='Tipo de regla a generar')]
    user_id: Annotated[
        str | None,
        Field(description='ID del usuario propietario (opcional)', title='User Id'),
    ] = None
    decision: Annotated[
        str | None, Field(description='Nombre de la decisión', title='Decision')
    ] = 'MAIN'
    sheet_name: Annotated[
        str | None, Field(description='Nombre de la hoja del Excel', title='Sheet Name')
    ] = 'Reglas BAM'
    allow_duplicates: Annotated[
        bool | None,
        Field(description='Permitir reglas duplicadas', title='Allow Duplicates'),
    ] = False


class BulkEvaluationResponseDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    results: Annotated[
        list[TransactionEvaluationResultDTO] | None,
        Field(
            description='Resultados de las evaluaciones de cada transacción.',
            title='Results',
        ),
    ] = None
    total_processed: Annotated[
        int,
        Field(
            description='Total de transacciones procesadas.',
            ge=0,
            title='Total Processed',
        ),
    ]
    total_success: Annotated[
        int,
        Field(
            description='Total de transacciones evaluadas exitosamente.',
            ge=0,
            title='Total Success',
        ),
    ]
    total_errors: Annotated[
        int,
        Field(
            description='Total de transacciones con errores.',
            ge=0,
            title='Total Errors',
        ),
    ]


class EvaluationRequestDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    tenant_id: Annotated[
        str,
        Field(
            description='Identificador del tenant.',
            examples=['01K0WPPET0GQH42G64B3Y2FPPJ'],
            min_length=1,
            title='Tenant Id',
        ),
    ]
    user_id: Annotated[
        str,
        Field(
            description='Identificador del usuario dentro del tenant.',
            examples=['user-123'],
            min_length=1,
            title='User Id',
        ),
    ]
    context: Annotated[
        TransactionFlowContextDTO,
        Field(
            description='Contexto tipado a evaluar por la decisión.',
            discriminator='flow_type',
            title='Context',
        ),
    ]
    decision: Annotated[
        str | None,
        Field(
            description='Nombre del archivo de decisión a utilizar.',
            examples=['MAIN', 'CUSTOM_DECISION'],
            title='Decision',
        ),
    ] = 'MAIN'


class ExcelImportResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    rules_imported: Annotated[
        int,
        Field(
            description='Número de reglas importadas exitosamente',
            title='Rules Imported',
        ),
    ]
    warnings: Annotated[
        list[str] | None,
        Field(description='Advertencias durante el procesamiento.', title='Warnings'),
    ] = None
    tenant_id: Annotated[str, Field(title='Tenant Id')]
    owner_id: Annotated[str | None, Field(title='Owner Id')]
    decision: Annotated[str, Field(title='Decision')]
    rule_type: RuleType


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None


class TransactionEvaluationRequestDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    context: Annotated[
        TransactionFlowContextDTO,
        Field(
            description='Contexto tipado de la transacción a evaluar (incluye transaction_id).',
            discriminator='flow_type',
            title='Context',
        ),
    ]


class BulkEvaluationRequestDTO(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    tenant_id: Annotated[
        str,
        Field(
            description='Identificador del tenant.',
            examples=['01K0WPPET0GQH42G64B3Y2FPPJ'],
            min_length=1,
            title='Tenant Id',
        ),
    ]
    user_id: Annotated[
        str,
        Field(
            description='Identificador del usuario dentro del tenant.',
            examples=['user-123'],
            min_length=1,
            title='User Id',
        ),
    ]
    transactions: Annotated[
        list[TransactionEvaluationRequestDTO],
        Field(
            description='Lista de transacciones a evaluar.',
            min_length=1,
            title='Transactions',
        ),
    ]
    decision: Annotated[
        str | None,
        Field(
            description='Nombre del archivo de decisión a utilizar.',
            examples=['MAIN', 'CUSTOM_DECISION'],
            title='Decision',
        ),
    ] = 'MAIN'

# Backwards compatibility aliases (DTO -> canonical)
BulkEvaluationRequest = BulkEvaluationRequestDTO
BulkEvaluationResponse = BulkEvaluationResponseDTO
EvaluationRequest = EvaluationRequestDTO
EvaluationResponse = EvaluationResponseDTO
TransactionData = TransactionDataDTO
TransactionEvaluationRequest = TransactionEvaluationRequestDTO
TransactionEvaluationResult = TransactionEvaluationResultDTO
TransactionFlowContext = TransactionFlowContextDTO
