# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-12-23T22:01:51+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BulkEmbeddingItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    id: Annotated[str, Field(description='Identificador único del item.', title='Id')]
    embedding: Annotated[
        list[float],
        Field(description='Vector de embedding generado.', title='Embedding'),
    ]


class Dimensions(RootModel[int]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[
        int, Field(description='Dimensión de los embeddings.', ge=0, title='Dimensions')
    ]


class BulkEmbeddingResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    model: Annotated[
        str, Field(description='Nombre del modelo utilizado.', title='Model')
    ]
    count: Annotated[
        int, Field(description='Número de embeddings generados.', ge=0, title='Count')
    ]
    dimensions: Annotated[
        Dimensions | None,
        Field(description='Dimensión de los embeddings.', title='Dimensions'),
    ] = None
    embeddings: Annotated[
        list[BulkEmbeddingItem],
        Field(
            description='Lista de embeddings con sus IDs correspondientes.',
            title='Embeddings',
        ),
    ]


class BulkItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    id: Annotated[str, Field(description='Identificador único del item.', title='Id')]
    description: Annotated[
        str, Field(description='Texto a convertir en embedding.', title='Description')
    ]


class EmbeddingRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    inputs: Annotated[
        list[str],
        Field(
            description='Textos a convertir en embeddings.',
            min_length=1,
            title='Inputs',
        ),
    ]
    model: Annotated[
        str | None,
        Field(
            description='Nombre del modelo solicitado. Si se omite se utilizará el modelo por defecto: snowflake/snowflake-arctic-embed-xs.',
            title='Model',
        ),
    ] = None


class EmbeddingResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    model: Annotated[
        str, Field(description='Nombre del modelo utilizado.', title='Model')
    ]
    count: Annotated[
        int, Field(description='Número de embeddings generados.', ge=0, title='Count')
    ]
    dimensions: Annotated[
        Dimensions | None,
        Field(description='Dimensión de los embeddings.', title='Dimensions'),
    ] = None
    embeddings: Annotated[
        list[list[float]],
        Field(
            description='Lista de embeddings en orden de entrada.', title='Embeddings'
        ),
    ]


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    status: Annotated[
        str, Field(description='Estado de salud de la API.', title='Status')
    ]
    model: Annotated[
        str,
        Field(description='Modelo configurado para generar embeddings.', title='Model'),
    ]


class ValidationError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    loc: Annotated[list[str | int], Field(title='Location')]
    msg: Annotated[str, Field(title='Message')]
    type: Annotated[str, Field(title='Error Type')]


class BulkEmbeddingRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    items: Annotated[
        list[BulkItem],
        Field(
            description='Lista de items con ID y descripción para generar embeddings.',
            min_length=1,
            title='Items',
        ),
    ]
    model: Annotated[
        str | None,
        Field(
            description='Nombre del modelo solicitado. Si se omite se utilizará el modelo por defecto: snowflake/snowflake-arctic-embed-xs.',
            title='Model',
        ),
    ] = None


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        frozen=True,
    )
    detail: Annotated[list[ValidationError] | None, Field(title='Detail')] = None

